name = "jacobi-identity"
defaultTargets = ["problem", "solution"]

[[require]]
name = "RogersRamanujan"
git = "https://github.com/AxiomMath/RogersRamanujan"
rev = "main"

[[lean_lib]]
name = "problem"
roots = ["problem"]

[[lean_lib]]
name = "solution"
roots = ["solution_updated"]
