name: ci

on:
  push:
    branches: [main]
    paths:
      - 'jacobi-identity/**'
      - 'jacobi-triple-product/**'
      - 'limit-topologically-nilpotent/**'
      - 'pentagonal-number-theorem/**'
      - 'pfaff-saalschuetz/**'
      - 'prescribed-open/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'jacobi-identity/**'
      - 'jacobi-triple-product/**'
      - 'limit-topologically-nilpotent/**'
      - 'pentagonal-number-theorem/**'
      - 'pfaff-saalschuetz/**'
      - 'prescribed-open/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: build (${{ matrix.folder }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder:
          - jacobi-triple-product
          - prescribed-open
          - pfaff-saalschuetz
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: leanprover/lean-action@38fbc41a8c28c4cbaec22d7f7de508ec2e7c0dd9 # v1.5.0
        with:
          lake-package-directory: ${{ matrix.folder }}
